name: Docker

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  fpm_push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Commit (PHP-FPM)

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: renokico/laravel-helm-demo:${{ github.sha }}
          file: Dockerfile.fpm

  octane_push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Commit (Octane)

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: renokico/laravel-helm-demo:octane-${{ github.sha }}
          file: Dockerfile.octane
